//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/FreeWebService")]
    public partial class CompositeType : object
    {
        
        private int NumarPaginaField;
        
        private int RezultatePaginaField;
        
        private string SearchAnField;
        
        private string SearchNumarField;
        
        private string SearchTextField;
        
        private string SearchTitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumarPagina
        {
            get
            {
                return this.NumarPaginaField;
            }
            set
            {
                this.NumarPaginaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RezultatePagina
        {
            get
            {
                return this.RezultatePaginaField;
            }
            set
            {
                this.RezultatePaginaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchAn
        {
            get
            {
                return this.SearchAnField;
            }
            set
            {
                this.SearchAnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchNumar
        {
            get
            {
                return this.SearchNumarField;
            }
            set
            {
                this.SearchNumarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchText
        {
            get
            {
                return this.SearchTextField;
            }
            set
            {
                this.SearchTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchTitlu
        {
            get
            {
                return this.SearchTitluField;
            }
            set
            {
                this.SearchTitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Legi", Namespace="http://schemas.datacontract.org/2004/07/FreeWebService")]
    public partial class Legi : object
    {
        
        private string DataVigoareField;
        
        private string EmitentField;
        
        private string LinkHtmlField;
        
        private string NumarField;
        
        private string PublicatieField;
        
        private string TextField;
        
        private string TipActField;
        
        private string TitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataVigoare
        {
            get
            {
                return this.DataVigoareField;
            }
            set
            {
                this.DataVigoareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emitent
        {
            get
            {
                return this.EmitentField;
            }
            set
            {
                this.EmitentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkHtml
        {
            get
            {
                return this.LinkHtmlField;
            }
            set
            {
                this.LinkHtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numar
        {
            get
            {
                return this.NumarField;
            }
            set
            {
                this.NumarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publicatie
        {
            get
            {
                return this.PublicatieField;
            }
            set
            {
                this.PublicatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipAct
        {
            get
            {
                return this.TipActField;
            }
            set
            {
                this.TipActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFreeWebService")]
public interface IFreeWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeWebService/GetToken", ReplyAction="http://tempuri.org/IFreeWebService/GetTokenResponse")]
    System.Threading.Tasks.Task<string> GetTokenAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreeWebService/Search", ReplyAction="http://tempuri.org/IFreeWebService/SearchResponse")]
    System.Threading.Tasks.Task<FreeWebService.Legi[]> SearchAsync(FreeWebService.CompositeType SearchModel, string tokenKey);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface IFreeWebServiceChannel : IFreeWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class FreeWebServiceClient : System.ServiceModel.ClientBase<IFreeWebService>, IFreeWebService
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public FreeWebServiceClient() : 
            base(FreeWebServiceClient.GetDefaultBinding(), FreeWebServiceClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.SoapEndPoint.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FreeWebServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(FreeWebServiceClient.GetBindingForEndpoint(endpointConfiguration), FreeWebServiceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FreeWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(FreeWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FreeWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(FreeWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public FreeWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<string> GetTokenAsync()
    {
        return base.Channel.GetTokenAsync();
    }
    
    public System.Threading.Tasks.Task<FreeWebService.Legi[]> SearchAsync(FreeWebService.CompositeType SearchModel, string tokenKey)
    {
        return base.Channel.SearchAsync(SearchModel, tokenKey);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.SoapEndPoint))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.SoapEndPoint))
        {
            return new System.ServiceModel.EndpointAddress("http://legislatie.just.ro/apiws/FreeWebService.svc/SOAP");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return FreeWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.SoapEndPoint);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return FreeWebServiceClient.GetEndpointAddress(EndpointConfiguration.SoapEndPoint);
    }
    
    public enum EndpointConfiguration
    {
        
        SoapEndPoint,
    }
}
